import 'package:xml/xml.dart';

/// One point read from a GPX track: a WGS84 position, its capture time, and
/// an optional recorded speed (some GPX flavors carry a `<speed>`
/// extension; none of this harness's fixtures emit one, so it is null in
/// practice, but callers that want to assert on recorded — not derived —
/// speed can use it).
class GpxPoint {
  final double lat;
  final double lon;
  final DateTime time;
  final double? speedMps;

  const GpxPoint({
    required this.lat,
    required this.lon,
    required this.time,
    this.speedMps,
  });
}

/// Parses a GPX 1.1 document's track points (`<trk>/<trkseg>/<trkpt>`) into
/// [GpxPoint]s, in document order.
///
/// Every fixture this harness plays back is generated by
/// `make_fixtures.dart` and always carries a `<time>` on each point — the
/// replay tests need real timestamps to drive [RouteFollower]'s off-route
/// timing and ETA — so a `<trkpt>` missing one indicates a broken fixture
/// rather than something to silently tolerate; it throws [ArgumentError]
/// with the offending point's coordinates.
List<GpxPoint> parseGpx(String xml) {
  final document = XmlDocument.parse(xml);
  final points = <GpxPoint>[];
  for (final trkpt in document.findAllElements('trkpt')) {
    final latAttr = trkpt.getAttribute('lat');
    final lonAttr = trkpt.getAttribute('lon');
    if (latAttr == null || lonAttr == null) {
      throw ArgumentError('gpx <trkpt> is missing a lat or lon attribute');
    }

    final timeElements = trkpt.findElements('time');
    if (timeElements.isEmpty || timeElements.first.innerText.isEmpty) {
      throw ArgumentError(
          'gpx <trkpt lat="$latAttr" lon="$lonAttr"> is missing a <time> '
          'child; every fixture in this harness must be fully timestamped');
    }

    final speedElements = trkpt.findElements('speed');
    final speedText =
        speedElements.isEmpty ? null : speedElements.first.innerText;

    points.add(GpxPoint(
      lat: double.parse(latAttr),
      lon: double.parse(lonAttr),
      time: DateTime.parse(timeElements.first.innerText),
      speedMps: speedText == null || speedText.isEmpty
          ? null
          : double.parse(speedText),
    ));
  }
  return points;
}
